=== K-kiron/IFT3225-TP/TP1/part2/schema_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Wenhao XU_20150702, Yuyang XIONG_20151236-->

<!ELEMENT bibliotheque (livres, auteurs) >
<!ELEMENT livres (livre+) >
<!ELEMENT auteurs (auteur+) >
<!ELEMENT livre (titre, annee, prix, couverture?, commentaire?) >
<!ELEMENT auteur (((nom,prenom)|(prenom,nom)), pays, commentaire?, photo) >
<!ELEMENT titre (#PCDATA) >
<!ELEMENT annee (#PCDATA) >
<!ELEMENT couverture (#PCDATA) >
<!ELEMENT commentaire (#PCDATA) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT pays (#PCDATA) >
<!ELEMENT photo (#PCDATA) >
<!ATTLIST livre langue CDATA #REQUIRED >
<!ATTLIST livre auteurs IDREFS #REQUIRED >
<!ATTLIST auteur auteurID ID #REQUIRED >
<!ATTLIST prix devise (CAD|USD|EURO) "CAD">

<!--Nous n'avons pas spécifié le type de contenu de l'attribut "prix", parce qu'il est de type
numérique mais il n'est pas en mesure de spécifier ce type avec DTD.-->

=== K-kiron/IFT3225-TP/TP1/part2/bibliotheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="schema_rnc.rnc" type="application/relax-ng-compact-syntax"?>
<!DOCTYPE bibliotheque SYSTEM "schema_dtd.dtd">
<bibliotheque>
    <livres>
        <livre langue="anglais" auteurs="a b">
            <titre></titre>
            <annee></annee>
            <prix></prix>
        </livre>
    </livres>
    
    <auteurs>
        <auteur auteurID="a">
            <nom></nom>
            <prenom></prenom>
            <pays></pays>
            <commentaire></commentaire>
            <photo></photo>
        </auteur>
        <auteur auteurID="b">
            <nom></nom>
            <prenom></prenom>
            <pays></pays>
            <photo></photo>
        </auteur>
    </auteurs>
</bibliotheque>
